/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.lbenda.dbapp.rc.frm;

import cz.lbenda.dbapp.rc.SessionConfiguration;
import cz.lbenda.dbapp.rc.db.DbStructureReader;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//cz.lbenda.dbapp.rc.frm//FrmDbSessionChooser//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "FrmDbSessionChooserTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "leftSlidingSide", openAtStartup = true)
@ActionID(category = "Window", id = "cz.lbenda.dbapp.rc.frm.FrmDbSessionChooserTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_FrmDbSessionChooserAction",
        preferredID = "FrmDbSessionChooserTopComponent"
)
@Messages({
  "CTL_FrmDbSessionChooserAction=FrmDbSessionChooser",
  "CTL_FrmDbSessionChooserTopComponent=FrmDbSessionChooser Window",
  "HINT_FrmDbSessionChooserTopComponent=This is a FrmDbSessionChooser window"
})
public final class FrmDbSessionChooserTopComponent extends TopComponent {

  public FrmDbSessionChooserTopComponent() {
    initComponents();
    setName(Bundle.CTL_FrmDbSessionChooserTopComponent());
    setToolTipText(Bundle.HINT_FrmDbSessionChooserTopComponent());

    listSessions.addMouseListener(new MouseAdapter() {
      @Override
      public void mousePressed(MouseEvent e) {
        if (e.getClickCount() == 2) {
          SessionConfiguration sc = SessionConfiguration.getConfiguration(String.valueOf(listSessions.getSelectedValue()));
          DbStructureReader.getInstance().setSessionConfiguration(sc);
        }
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    listSessions = new javax.swing.JList();

    jScrollPane1.setViewportView(listSessions);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JList listSessions;
  // End of variables declaration//GEN-END:variables
  @Override
  public void componentOpened() {
    DefaultListModel dlm = new DefaultListModel();
    for (String name : SessionConfiguration.getConfigurationIDs()) { dlm.addElement(name); }
    listSessions.setModel(dlm);
  }

  @Override
  public void componentClosed() {
    // TODO add custom code on component closing
  }

  void writeProperties(java.util.Properties p) {
    // better to version settings since initial version as advocated at
    // http://wiki.apidesign.org/wiki/PropertyFiles
    p.setProperty("version", "1.0");
    // TODO store your settings
  }

  void readProperties(java.util.Properties p) {
    String version = p.getProperty("version");
    // TODO read your settings according to their version
  }
}
