drop table DATAMAN.T_NUM;
drop table DATAMAN.T_CHAR;
drop table DATAMAN.T_BB;
drop table DATAMAN.T_TIME;
drop schema DATAMAN;
create schema DATAMAN;

create table DATAMAN.T_NUM (
  ID integer generated by default as identity(start with 0) primary key,
  CTINYINT tinyint,
  CSMALLINT smallint,
  CINTEGER integer,
  CBIGINT bigint,
  CNUMERIC numeric(8,3),
  CDECIMAL decimal(15,5)
);
insert into DATAMAN.T_NUM (ctinyint, csmallint, cinteger, cbigint, cnumeric, cdecimal)
values (10, 20, 30, 40, 900.08, 50000.898);

create table DATAMAN.T_CHAR (
  CCHAR char(1024) not null,
  CVARCHAR varchar(1024),
  CLONGVARCHAR longvarchar,
  CCLOB clob,
  primary key(CCHAR)
);
insert into DATAMAN.T_CHAR (CCHAR) values('pk1');
insert into DATAMAN.T_CHAR (CCHAR, CVARCHAR) values('pk2', 'varchar');
insert into DATAMAN.T_CHAR (CCHAR, CLONGVARCHAR) values('pk3', 'longvarchar');
insert into DATAMAN.T_CHAR (CCHAR, CCLOB) values('pk4', 'clob valus in clob');

create table DATAMAN.T_BB (
  CBOOLEAN boolean,
  CBIT bit,
  CBITL bit(15),
  CBINARY binary(50),
  CVARBINARY varbinary(588),
  CLONGVARBINARY longvarbinary,
  BLOB blob
);
insert into DATAMAN.T_BB (CBOOLEAN) values(true);
insert into DATAMAN.T_BB (CBIT) values(1);
insert into DATAMAN.T_BB (CBITL) values('101010101010101');
insert into DATAMAN.T_BB (CBITL) values('111100001010101');
insert into DATAMAN.T_BB (CBITL) values('000000000000000');
insert into DATAMAN.T_BB (CBINARY) values(x'a1b2c501020304050612');
insert into DATAMAN.T_BB (CVARBINARY) values(x'a1b2c501020304050612');
insert into DATAMAN.T_BB (CLONGVARBINARY) values(x'a1b2c501020304050612');
insert into DATAMAN.T_BB (BLOB) values(x'a1b2c501020304050612');

create table DATAMAN.T_TIME (
  ID char(1024) not null,
  CDATE date,
  CTIME time,
  CTIMESTAMP timestamp,
  CINTERVAL interval YEAR TO MONTH, 
  primary key(ID)
);
insert into DATAMAN.T_TIME (ID, CDATE, CTIME, CTIMESTAMP) 
values ('1', '2005-12-12', '15:15:15.015', '2005-12-12 15:15:15.015');
insert into DATAMAN.T_TIME (ID, CINTERVAL) 
values ('2', 15);
insert into DATAMAN.T_TIME (ID, CINTERVAL) 
values ('2', '02-10');
